config/routes.rb
Rails.application.routes.draw do

    resources :users
    resources :echogram_temps, only: [:new,:create,:index,:show,:destroy]
    resources :composition_temps,only:[:new,:create,:destroy]

    get    '/new',          to: 'sessions#new'    
    get    '/home',         to: 'homepage#home'
    get    '/pdf',          to: 'homepage#pdf'
    get    '/search',       to: 'homepage#search'
    get    '/querygram',    to: 'query#querygram'
    get    '/details',      to: 'query#details'
    get    '/submit',       to: 'upload#submit'
    get    '/confirm',      to: 'upload#confirm'
    get    '/accept',       to: 'upload#accept'
    get    '/reject',       to: 'upload#reject'    
    get    '/signup',       to: 'users#new'
    post   '/signup',       to: 'users#create'
    get    '/login',        to: 'sessions#new'
    post   '/login',        to: 'sessions#create'
    delete '/logout',       to: 'sessions#destroy'


    root 'homepage#home'
    
end

app/models/echogram_temp.rb
class EchogramTemp < ApplicationRecord

    has_one_attached :gram
    # allows destroying an echogram via a profile's update action
    accepts_nested_attributes_for :gram_attachment, allow_destroy: true  

    validate :lat_valid
    validate :long_valid
    validate :gram_valid
    validates_uniqueness_of :image_filename, message: "Image file name already exists."


   
    
    private
      def lat_valid
        if latitude.empty?
            errors.add :echogram_temp, 'Latitude input is empty' 
        else   
          if float_valid?(latitude)    
            if latitude.to_f > 90 || latitude.to_f < -90 
              errors.add :echogram_temp, 'Latitude is out of range.' 
            end
          else
            errors.add :echogram_temp, 'Latitude input invalid.' 
          end
        end
      end

      def long_valid
        if longitude.empty?
            errors.add :echogram_temp, 'Longitude input is empty' 
        else    
          if float_valid?(longitude)
            if longitude.to_f > 180 || longitude.to_f < -180 
              errors.add :echogram_temp, 'Longitude is out of range.' 
            end
          else
            errors.add :echogram_temp, 'Longitude input invalid.' 
          end
        end
      end

      def gram_valid
        if gram.attached?
            if gram.image?()
                name_valid(gram.filename.to_s)
                size_valid
            else  
                errors.add :gram, 'Your uploadding is not an image file.' 
            end      
        else
            errors.add :gram, 'You did not choose any image.' 
        end
      end

      def gram_conflict      
        image_name_filter = gram.filename.to_s
        if can_upload?              
            if duplicate_filename?(image_name_filter)
              errors.add :gram, 'Echogram image file name already exists.' 
            else
              gram_filter = image_name_filter[0,24]
              if gramname_comflict?(gram_filter)
                errors.add :gram, 'Echogram name conflict with other user uploading' 
              end
            end
        end
      end

      def size_valid
          if gram.byte_size > (3*1024*1024)  
            errors.add :gram, 'Image file size is too big.'
          end  
      end

      def name_valid(imagename)
        if imagename_downcase_valid?(imagename)
            if imagename_prefix_valid?(imagename)
              if format_valid?(imagename)
                  unless type_valid?(imagename)
                    errors.add :gram, 'File format invalid.'
                  end
                  unless dot_valid?(imagename)
                    errors.add :gram, 'There should be one and only one "." contained in filenane.'
                  end
                  unless  imagename_date_valid?(imagename)
                    errors.add :gram, 'Fishing date invalid'
                  end
                  unless imagename_time_valid?(imagename)
                    errors.add :gram, 'Start fishing time invalid'
                  end
              else
                  errors.add :gram, 'Name format invalid'
              end                  
            else
              errors.add :gram, 'Image file name should start with "echogram_".'
            end

        else
            errors.add :gram, 'All letters should be in downcase.' 
        end
      end

      def imagename_downcase_valid?(name)
        match = true
        name.each_char do |r|
          if (65..90).cover?(r.ord)
            match = false
          end
        end
        return match
      end

      def imagename_prefix_valid?(name)        
        return name[0,9] == "echogram_" 
      end

      def imagename_date_valid?(name)
        b1 = (1990..2030).cover?(name[9,4].to_i) 
        b2 = (0..12).cover?(name[13,2].to_i) 
        b3 = (0..31).cover?(name[15,2].to_i) 
        match = b1&&b2&&b3
        return match
      end

      def imagename_time_valid?(name)
        b1 = (0..23).cover?(name[18,2].to_i) 
        b2 = (0..59).cover?(name[20,2].to_i) 
        b3 = (0..59).cover?(name[22,2].to_i) 
        match = b1&&b2&&b3
        return match
      end

      def format_valid?(name)
        b1 = name[17] == "_" 
        b2 = name[24] == "_" 
        b3 = name[29] == "." 
        match = b1&&b2&&b3
        return match
      end

      def dot_valid?(name)
        num = name.count(".")
        if num == 1 
          return true
        else 
          return false
        end
      end

      def type_valid?(name)
        temp   = name.split(".")
        format = temp[1]  
        match  = ["gif","jpg","jpeg","png"].include?(format)
        return match
      end

      #to judge whether an input is a valid float number form
      def float_valid?(input)
        temp = input.to_s
        true_num = true
        #invalid input if there are more than one "."
        #and start with "."
        dot_num = temp.count(".")  
        if dot_num != 0
          if dot_num > 1
            true_num = false
          end
          if temp.index(".") == 0
            true_num = false
          end
        end
        #invalid input if there are more than one "-"
        #and not start with "-"
        minus_num = temp.count("-")
        if minus_num != 0
          if minus_num > 1
            true_num = false
          end
          if temp.index("-") != 0
            true_num = false
          end
        end
      
        #invalid input if there are other symbols
        temp.each_char do |r|
            flag = (45..57).cover?(r.ord) && r.ord != 47
            if !flag
                true_num = false
            end
        end
        return true_num
      end  
  end

app/controllers/echogram_temps_controller.rb
class EchogramTempsController < ApplicationController

  before_action :logged_in_user, only: [:new,:create,:index,:show,:destroy]
  before_action :set_echogram_temp, only: [:update, :destroy]
  before_action :display_composition, only: [:show]

  def index
    @echogram_temps = EchogramTemp.all
    temp = EchogramTemp.all.where(user_id: session[:user_id])
    sorted = temp.order(created_at: :desc)
    @display = sorted.paginate(page: params[:page],per_page: 10)
  end

  def show
  end

  def new
    @echogram_temp = EchogramTemp.new
  end

  def create
    all_params = echogram_temp_params
    @echogram_temp = EchogramTemp.new(echogram_temp_params)

    if all_params[:gram]
        lat      = all_params[:latitude]
        long     = all_params[:longitude]
        filename = all_params[:gram].original_filename.to_s
        gramname = filename[0,24]
        freq     = filename[25,4].to_i
        userid   = session[:user_id] 

        @echogram_temp.update(
          echogram_name:  gramname,
          image_filename: filename,
          frequency:      freq,
          user_id:        userid,
          editable:       true
        )
    end
   
    if @echogram_temp.save
      flash[:success] = "Image successfully uploaded."
      redirect_to echogram_temps_url
    else
      render 'new'
    end

  end

  def destroy
    name = @echogram_temp.echogram_name
    comp = CompositionTemp.where(echogram_name:name)
    num = comp.count
   
    #delete associated species compositions
    if num > 0
      comp.destroy_all
    end

    #delete attached image file
    @echogram_temp.gram.purge

    #delete echogram_temp
    @echogram_temp.destroy
    redirect_to echogram_temps_url
    flash[:success] = "Echogram temp was successfully deleted."
  end

  private
    def set_echogram_temp
      @echogram_temp = EchogramTemp.find(params[:id])
    end

    def display_composition
      temp = set_echogram_temp
      name = temp.echogram_name
      @composition = CompositionTemp.all.where(echogram_name:name)
    end

    def echogram_temp_params
      params.require(:echogram_temp).permit(
        :image_filename, 
        :longitude,
        :latitude,
        #Allow uploading a single file
        :gram,       
        # Allow destroying a gram
        gram_attachment_attributes: [:id, :_destroy] 
      )
    end

end

app/views/echogram_temps/_form.html.erb
<%= form_with(model: echogram_temp, local: true) do |form| %>

  <% if echogram_temp.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(echogram_temp.errors.count, "errors") %> occured:</h3>
      <ul>
      <% echogram_temp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag "Latitude:" %>
    <%= form.text_field :latitude %>
  </div>

  <br>

  <div class="field">
    <%= label_tag "Longitude:" %>
    <%= form.text_field :longitude %>
  </div>

  <br>

  <div class="field">
    <%= label_tag "Select an image:" %>
    <%= form.file_field :gram %>

    <% if echogram_temp.gram.attached? && echogram_temp.gram.representable? %>
      <br>
      <%= image_tag(echogram_temp.gram.representation(resize: '250x250').processed) %>
    <% end %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit "Upload",  class:"btn btn-primary btn-block btn-lg"%>
  </div>

<% end %>

app/views/echogram_temps/index.html.erb
<div class = "container">
    <h3>My uploads: <a href="#" onclick="return false;" data-toggle="popover" 
          data-trigger="focus" data-placement="right"  title="How it works?" 
          data-content="1) Click on the Echogram images to show and add Echogram details
                        2) Use Upload New Images button to upload a new image
                        3) Use Confirm Uploading to verify your upload 
                        3) Use Delete button to delete the entire record">
          <span class="glyphicon glyphicon-info-sign" style="font-size:20px;"></span></a></h3> <br>
  <div class="table-responsive">
    <table class="table table-hover">
     
        <% @display.each do |item| %>
          <tr>                
              <td>
                  <% if item.gram.attached? %>            
                      <%= link_to image_tag(item.gram.representation(resize: '200x150').processed),item %> 
                  <% end %> 
              </td>

              <td> 
                  <%= item.image_filename %> 
                  <br>                                       
                  <br>
                  <% if item.editable %>
                     <%= link_to "Delete", item, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-lg"    %> 
                  <% end %>
              </td>
          </tr>
        <% end %>
      
    </table>
  </div>

  

    <div class="col-md-offset-2 col-lg-offset-2 col-xl-offset-2">
      <%= will_paginate @display%>
    </div>

    <% if @display.count == 0 %>
        <p> You haven't uploaded any images.<p>  
        <br> 
        <%= link_to 'Back', :back, class:"btn btn-default btn-lg", style:"margin-right:20px" %>
        <%= link_to 'Upload New Images', new_echogram_temp_path, class:"btn btn-primary btn-lg", style:"margin-right:20px" %>
    <% else %> 
        <%= link_to 'Back', :back, class:"btn btn-default btn-lg", style:"margin-right:20px" %>
        <%= link_to 'Upload New Images', new_echogram_temp_path, class:"btn btn-primary btn-lg", style:"margin-right:20px" %>
        <%= link_to  button_tag("Confirm Uploading", data: { confirm: "Are you sure?" }, class:"btn btn-success btn-lg" ), submit_path %>
    <% end %>       
</div>


<script>
$(function () {
  $('[data-toggle="popover"]').popover()
})
</script>

app/views/echogram_temps/new.html.erb
<div class ="container">

    <h2> Uploading Rules </h2>
    <br>

    <div class="uploadpage">    

        <p> 
        <strong>Please follow these rules to successfully upload your Echogram image</strong>
        <br><br>
        The image file name must be downcase and must have this format: echogram_yyyymmdd_hhmmss_ffff.gif
        <br><br>
        Where:
        <br>
        <li><strong>yyyymmdd</strong> is the fishing date (eg.20200722 stands for July 22th 2020)</li>
        <li><strong>hhmmss</strong> is the start fishing time (eg.233009 stands for 23:30:09)</li>
        <li><strong>ffff</strong> is frequency (eg. 38kHz should be 0038,120kHz should be 0120)</li>
        <br>
        The suported image format are gif,png,jpg,jpeg 
        <br>
        Image size should be within 3 MB 
        <br><br>
        Longitude range is (-180,180)
        <br>
        Latitude range is (-90,90)       
        </p>

    </div>

    <br>

    <h2>Upload your Echogram here <a href="#" onclick="return false;" data-toggle="popover" 
          data-trigger="focus" data-placement="left"  title="How it works?" 
          data-content="1) Add the latitude and longitude in the blank space
                        2) Select Choose file button to brows your image
                        3) Clik on the Upload button">
          <span class="glyphicon glyphicon-info-sign" style="font-size:20px;"></span></a></h2>

    <br>

    <%= render 'form', echogram_temp: @echogram_temp %> <br><br>
    <%= link_to 'Back', :back, class:"btn btn-default btn-lg", style:"margin-right:20px"%>
    <%= link_to 'My upload', echogram_temps_path, class:"btn btn-default btn-lg" %>

</div>

<script>
$(function () {
  $('[data-toggle="popover"]').popover()
})
</script>

app/views/echogram_temps/show.html.erb
<div class="container">
  <div class="uploadpage">
      <h2>Image Features</h2> <br>

      <p>
        <strong>Echogram name:</strong>
        <%= @echogram_temp.echogram_name %>
      </p>

      <p>
        <strong>Image filename:</strong>
        <%= @echogram_temp.image_filename %>
      </p>

      <p>
        <strong>Frequency:</strong>
        <%= @echogram_temp.frequency %> kHz
      </p>

      <p>
        <strong>Latitude:</strong>
        <%= @echogram_temp.latitude %>
      </p>

      <p>
        <strong>Longitude:</strong>
        <%= @echogram_temp.longitude %>
      </p>

      <p>
        <strong>Byte size: </strong> <%= @echogram_temp.gram.byte_size/1024 %> kb
      </p>


      <p>
        <strong>Image width: </strong> <%= @echogram_temp.gram.metadata[:width] %> pix
      </p>

      <p>
        <strong>Image height:</strong> <%= @echogram_temp.gram.metadata[:height] %> pix
      </p>

      <p>
        <strong> Echogram Image: </strong> <br><br>
        <% if @echogram_temp.gram.attached? %>
            <%= image_tag(@echogram_temp.gram.representation(resize: '400x300').processed) %>
        <% end %>
      </p>
  </div>

  <br>

<% if @echogram_temp.editable %> 
    <% if @composition.count != 0 %>
        <h3>
          Species Composition: <a href="#" onclick="return false;" data-toggle="popover" 
            data-trigger="focus" data-placement="right"  title="How it works?" 
            data-content="1) Use Add Species Composition button to add the species to your Echogram image">
            <span class="glyphicon glyphicon-info-sign" style="font-size:20px;"></span></a>
        </h3>
        <div class="table-responsive">
              <table class="table table-bordered">
                  <thead class="thead-dark">
                      <tr>
                        <th> Species </th>
                        <th> Numbers </th>   
                        <th> Mean length </th> 
                        <th> Operation </th>      
                      </tr>
                  </thead>

                  <tbody>
                      <% @composition.each do |item| %>
                        <tr>
                            <td> <%= item.species %> </td>
                            <td> <%= item.numbers %> </td>
                            <td> <%= item.mean_length %> </td>
                            <td> 
                                <%= link_to "Delete", composition_temp_path(:comp_id => item.id, :gram_id => params[:id]), 
                                                      method: :delete, 
                                                      data: {gram_id: params[:id], 
                                                      confirm: 'Are you sure?' }  %> 
                            </td>
                        </tr>
                      <% end %>
                  </tbody>
              </table>
        </div>
    <% end%>

    <br>

    <%= link_to 'Back', echogram_temps_path, class:"btn btn-default btn-lg", style:"margin-right:20px" %> 
    <%= link_to 'Add Compositions', new_composition_temp_path(:gram_id => params[:id]), class:"btn btn-primary btn-lg"%>
<% else %> 
    <% if @composition.count != 0 %>
      <h3>
        Species Composition:
      </h3>
      <div class="table-responsive">
              <table class="table table-bordered">
                  <thead class="thead-dark">
                      <tr>
                        <th> Species </th>
                        <th> Numbers </th>   
                        <th> Mean length </th>    
                      </tr>
                  </thead>
                  <tbody>
                      <% @composition.each do |item| %>
                        <tr>
                            <td> <%= item.species %> </td>
                            <td> <%= item.numbers %> </td>
                            <td> <%= item.mean_length %> </td>
                        </tr>
                      <% end %>
                  </tbody>
              </table>
      </div>
    <% end%>
    <%= link_to 'Back', echogram_temps_path,  class:"btn btn-default btn-lg"%>
<% end %> 

</div>



<script>
$(function () {
  $('[data-toggle="popover"]').popover()
})
</script>