config/routes.rb
Rails.application.routes.draw do

    resources :users
    resources :echogram_temps, only: [:new,:create,:index,:show,:destroy]
    resources :composition_temps,only:[:new,:create,:destroy]

    get    '/new',          to: 'sessions#new'    
    get    '/home',         to: 'homepage#home'
    get    '/pdf',          to: 'homepage#pdf'
    get    '/search',       to: 'homepage#search'
    get    '/querygram',    to: 'query#querygram'
    get    '/details',      to: 'query#details'
    get    '/submit',       to: 'upload#submit'
    get    '/confirm',      to: 'upload#confirm'
    get    '/accept',       to: 'upload#accept'
    get    '/reject',       to: 'upload#reject'    
    get    '/signup',       to: 'users#new'
    post   '/signup',       to: 'users#create'
    get    '/login',        to: 'sessions#new'
    post   '/login',        to: 'sessions#create'
    delete '/logout',       to: 'sessions#destroy'


    root 'homepage#home'
    
end

app/views/layouts/_footer.html.erb




<div class=" footer">         <!--<div class="mt-5 pt-5 pb-5 footer">-->
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-5 col-sm-6 about-company">
      <h4>EchoLib</h4> 
      <p class="pr-5 text-white-50"> The purpose of this web application is to create a searchable online database where echotraces of the major commercial fish schools in the north European sea can be stored and accessed.</p>
      <img src="/images/logo.png" style="width:50px;height:50px;float:center;" class="img-responsive">
    </div>
    <div class="col-lg-3 col-sm-6 links">
      <h4 class="mt-lg-0 mt-sm-3">Useful Links</h4>
        <ul class="list-unstyled">
          <li>- <%= link_to "Sign Up", signup_path, style:"font-size:15px" %></li>
          <li>- <%= link_to "My Uploads", echogram_temps_path,  style:"font-size:15px"%></li>
          <li>- <%= link_to "Search", querygram_path, style:"font-size:15px" %></li>
          <li>- <%= link_to "Upload", new_echogram_temp_path, style:"font-size:15px" %></li>
        </ul>
    </div>
    <div class="col-lg-4 col-sm-6 location">
      <h4 class="mt-lg-0 mt-sm-4">Contact Us</h4>
      <p>School of Biological Sciences, Zoology Building, University of Aberdeen, Tillydrone Avenue, Aberdeen, AB24 2TZ </p>
      <p class="mb-0"><span class="glyphicon">&#xe182;</span> +44 (0)1224-274166</p>
      <p><span class="glyphicon">&#x2709;</span> fernandespg@abdn.ac.uk</p>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col copyright">
      <p class=""><small class="text-white-50" >&copy; 2020 - University of Aberdeen </small></p>
    </div>
  </div>
</div>
</div>


<!--style code from https://codepen.io/anu-uxe/pen/drJERE by anu.uxe-->

app/views/layouts/_header.html.erb


<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container-fluid">
       <a class="navbar-brand"><img src="/images/logo.png" style="width:50px;height:50px;" class="img-responsive"></a>
       <%= link_to "EchoLib", root_path, class: "logo" %>      
        <nav>
          <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed"
                      data-toggle="collapse"
                      data-target="#bs-example-navbar-collapse-1"
                      aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
          </div>
          <div class="collapse navbar-collapse"
                id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><%= link_to "Home",          root_path %></li>
              <li><%= link_to "Query",         querygram_path %></li>
              <li><%= link_to "Upload",        new_echogram_temp_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Help",          pdf_path, target: :_blank %></li>
              <li><%= link_to "SignUp",        signup_path %></li>
              <% if logged_in? %>
                   <% if current_user.admin? %>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Account <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                          <li><%= link_to "My Profile", current_user %></li>
                          <li><%= link_to "All Users", users_path %></li>
                          <li class="divider"></li>
                          <li>
                            <%= link_to "Log out", logout_path, method: :delete %>
                          </li>
                        </ul>
                      </li>
                   <% else %>
                        <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Account <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                          <li><%= link_to "My Profile", current_user %></li>
                          <li><%= link_to "MyUpload", echogram_temps_path %></li>
                          <li class="divider"></li>
                          <li>
                            <%= link_to "Log out", logout_path, method: :delete %>
                          </li>
                        </ul>
                      </li>
                   <% end %>
              <% else %>
                <li><%= link_to "Log in", login_path %></li>
              <% end %>
           </ul>
          </div>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head> 
    <% #change the title of a page. CONFUSED %>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>


  <body>
    <%= render 'layouts/header' %>
    <div class="container" id="page-container">
    <div id="content-wrap">
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </div>
    </div>

    <div id="page-container">
     <%= render 'layouts/footer' %>
    </div>
    
  </body>
</html>